### Diferença de desistências entre 2019 e 2020 por estado
Importar os dados do enem de 2019 e 2020

In [1]:
import pandas as pd
df2019 = pd.read_csv('MICRODADOS_ENEM_2019.csv', sep=';', encoding='latin-1')

In [2]:
df2020 = pd.read_csv('MICRODADOS_ENEM_2020.csv', sep=';', encoding='latin-1')

Selecionar somente participantes com o ano de conclusão igual ao ano de realização da prova

Para o cálculo de abstenção, conta-se pessoas que faltaram no primeiro dia de prova ou no segundo dia de prova

In [17]:
import numpy as np
df_enem2019 = df2019[df2019['TP_ST_CONCLUSAO'] == 2] #Situação de conclusão do Ensino Médio
df_abstencao2019 = df_enem2019[np.logical_or(df_enem2019['TP_PRESENCA_CH'] == 0, df_enem2019['TP_PRESENCA_CN'] == 0)]

In [18]:
df_enem2020 = df2020[df2020['TP_ST_CONCLUSAO'] == 2] #Situação de conclusão do Ensino Médio
df_abstencao2020 = df_enem2020[np.logical_or(df_enem2020['TP_PRESENCA_CH'] == 0, df_enem2020['TP_PRESENCA_CN'] == 0)]

#### Preparação dos dados de 2019

In [19]:
df_abstencao2019.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 248015 entries, 3 to 5095245
Columns: 136 entries, NU_INSCRICAO to Q025
dtypes: float64(24), int64(71), object(41)
memory usage: 259.2+ MB

In [20]:
df_enem2019.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1465895 entries, 2 to 5095258
Columns: 136 entries, NU_INSCRICAO to Q025
dtypes: float64(24), int64(71), object(41)
memory usage: 1.5+ GB

Agrupar as desistências de 2019 e dividir pela quantidade total de pessoas em 2019 pelo lugar que o participante estudou

In [21]:
abstencao_estados2019 = df_abstencao2019.groupby(['SG_UF_PROVA']).size() / df_enem2019.groupby(['SG_UF_PROVA']).size() * 100
abstencao_estados2019 = abstencao_estados2019.to_frame().reset_index()
#Renomear as colunas como padronização
abstencao_estados2019 = abstencao_estados2019.rename(columns={'SG_UF_PROVA': 'estado'})
abstencao_estados2019 = abstencao_estados2019.rename(columns={0: 'abstencao 2019'})
abstencao_estados2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   estado          27 non-null     object
 1   abstencao 2019  27 non-null     float64
dtypes: float64(1), object(1)
memory usage: 560.0+ bytes

Ordenar por taxa de abstenção

In [22]:
abstencao_estados2019 = abstencao_estados2019.sort_values(by='abstencao 2019',ascending=False)
abstencao_estados2019

   estado  abstencao 2019
2      AM       22.477882
21     RR       20.912052
5      CE       20.884185
20     RO       19.787962
17     PR       19.741172
23     SC       18.954189
25     SP       18.947925
12     MT       17.812226
11     MS       16.648967
15     PE       16.502362
22     RS       16.354375
3      AP       16.100072
9      MA       16.037491
10     MG       15.713177
18     RJ       15.363514
26     TO       15.235711
4      BA       15.183041
0      AC       15.157480
7      ES       15.089325
8      GO       14.865874
13     PA       14.446901
1      AL       14.368690
24     SE       12.917042
6      DF       12.696782
14     PB       12.492049
16     PI       12.349074
19     RN       12.202300

#### Preparação dos dados de 2020

Agrupar as desistências de 2020 e dividir pela quantidade total de pessoas em 2020 pelo lugar que o participante estudou

In [23]:
abstencao_estados2020 = df_abstencao2020.groupby(['SG_UF_PROVA']).size() / df_enem2020.groupby(['SG_UF_PROVA']).size() * 100
abstencao_estados2020 = abstencao_estados2020.to_frame().reset_index()
#Renomear as colunas como padronização
abstencao_estados2020 = abstencao_estados2020.rename(columns={'SG_UF_PROVA': 'estado'})
abstencao_estados2020 = abstencao_estados2020.rename(columns={0: 'abstencao 2020'})
abstencao_estados2020

   estado  abstencao 2020
0      AC       36.375940
1      AL       38.177685
2      AM       61.273039
3      AP       40.894661
4      BA       33.657117
5      CE       49.464867
6      DF       31.398619
7      ES       36.756404
8      GO       49.935913
9      MA       39.128214
10     MG       38.309423
11     MS       43.395279
12     MT       43.059220
13     PA       37.622665
14     PB       33.011577
15     PE       42.233237
16     PI       32.877132
17     PR       40.135051
18     RJ       38.459439
19     RN       31.054131
20     RO       58.253427
21     RR       49.171566
22     RS       38.262636
23     SC       45.568778
24     SE       37.113124
25     SP       43.515856
26     TO       49.071758

Ordenar por taxa de abstenção

In [24]:
abstencao_estados2020 = abstencao_estados2020.sort_values(by='abstencao 2020',ascending=False)
abstencao_estados2020

   estado  abstencao 2020
2      AM       61.273039
20     RO       58.253427
8      GO       49.935913
5      CE       49.464867
21     RR       49.171566
26     TO       49.071758
23     SC       45.568778
25     SP       43.515856
11     MS       43.395279
12     MT       43.059220
15     PE       42.233237
3      AP       40.894661
17     PR       40.135051
9      MA       39.128214
18     RJ       38.459439
10     MG       38.309423
22     RS       38.262636
1      AL       38.177685
13     PA       37.622665
24     SE       37.113124
7      ES       36.756404
0      AC       36.375940
4      BA       33.657117
14     PB       33.011577
16     PI       32.877132
6      DF       31.398619
19     RN       31.054131

#### Dataframe final
Junção dos dataframes de 2019 e 2020 por estado

In [25]:
df_taxas = pd.merge(abstencao_estados2020, abstencao_estados2019, how = 'inner', on = 'estado')

Alteração de UF para nome dos estados

In [26]:
UF_dict = { 'AC':'Acre',
            'AL':'Alagoas',
            'AP':'Amapá',
            'AM':'Amazonas',
            'BA':'Bahia',
            'CE':'Ceará',
            'DF':'Distrito Federal',
            'ES':'Espírito Santo',
            'GO':'Goiás',
            'MA':'Maranhão',
            'MT':'Mato Grosso',
            'MS':'Mato Grosso do Sul',
            'MG':'Minas Gerais',
            'PA':'Pará',
            'PB':'Paraíba',
            'PR':'Paraná',
            'PE':'Pernambuco',
            'PI':'Piauí',
            'RJ':'Rio de Janeiro',
            'RN':'Rio Grande do Norte',
            'RS':'Rio Grande do Sul',
            'RO':'Rondônia',
            'RR':'Roraima',
            'SC':'Santa Catarina',
            'SP':'São Paulo',
            'SE':'Sergipe',
            'TO':'Tocantins'}

In [27]:
df_taxas["estado"] = df_taxas["estado"].replace(UF_dict)
# Estado como idex
df_taxas.set_index('estado',inplace = True)
df_taxas

                     abstencao 2020  abstencao 2019
estado
Amazonas                  61.273039       22.477882
Rondônia                  58.253427       19.787962
Goiás                     49.935913       14.865874
Ceará                     49.464867       20.884185
Roraima                   49.171566       20.912052
Tocantins                 49.071758       15.235711
Santa Catarina            45.568778       18.954189
São Paulo                 43.515856       18.947925
Mato Grosso do Sul        43.395279       16.648967
Mato Grosso               43.059220       17.812226
Pernambuco                42.233237       16.502362
Amapá                     40.894661       16.100072
Paraná                    40.135051       19.741172
Maranhão                  39.128214       16.037491
Rio de Janeiro            38.459439       15.363514
Minas Gerais              38.309423       15.713177
Rio Grande do Sul         38.262636       16.354375
Alagoas                   38.177685       14.368690
Pará                      37.622665       14.446901
Sergipe                   37.113124       12.917042
Espírito Santo            36.756404       15.089325
Acre                      36.375940       15.157480
Bahia                     33.657117       15.183041
Paraíba                   33.011577       12.492049
Piauí                     32.877132       12.349074
Distrito Federal          31.398619       12.696782
Rio Grande do Norte       31.054131       12.202300

Calcular a diferença entre os anos, ou seja, a taxa de abstenção de 2020 menos a taxa de abstenção de 2019

In [28]:
df_taxas['diferenca'] = df_taxas['abstencao 2020'] - df_taxas['abstencao 2019']
df_taxas

                     abstencao 2020  abstencao 2019  diferenca
estado
Amazonas                  61.273039       22.477882  38.795158
Rondônia                  58.253427       19.787962  38.465465
Goiás                     49.935913       14.865874  35.070039
Ceará                     49.464867       20.884185  28.580682
Roraima                   49.171566       20.912052  28.259514
Tocantins                 49.071758       15.235711  33.836046
Santa Catarina            45.568778       18.954189  26.614589
São Paulo                 43.515856       18.947925  24.567931
Mato Grosso do Sul        43.395279       16.648967  26.746312
Mato Grosso               43.059220       17.812226  25.246995
Pernambuco                42.233237       16.502362  25.730875
Amapá                     40.894661       16.100072  24.794589
Paraná                    40.135051       19.741172  20.393879
Maranhão                  39.128214       16.037491  23.090723
Rio de Janeiro            38.459439       15.363514  23.095924
Minas Gerais              38.309423       15.713177  22.596246
Rio Grande do Sul         38.262636       16.354375  21.908261
Alagoas                   38.177685       14.368690  23.808995
Pará                      37.622665       14.446901  23.175765
Sergipe                   37.113124       12.917042  24.196082
Espírito Santo            36.756404       15.089325  21.667079
Acre                      36.375940       15.157480  21.218460
Bahia                     33.657117       15.183041  18.474075
Paraíba                   33.011577       12.492049  20.519528
Piauí                     32.877132       12.349074  20.528058
Distrito Federal          31.398619       12.696782  18.701838
Rio Grande do Norte       31.054131       12.202300  18.851831

Exportar o dataframe

In [29]:
#df_taxas.to_csv("taxas_abstencao.csv")